# Generated by Django 4.2 on 2024-02-29 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lliga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('equip_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='lliga.equip')),
                ('equip_visitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitant', to='lliga.equip')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('edat', models.IntegerField()),
                ('nacionalitat', models.CharField(max_length=100)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lliga.equip')),
            ],
        ),
        migrations.AddField(
            model_name='equip',
            name='lligues',
            field=models.ManyToManyField(to='lliga.lliga'),
        ),
    ]
