# Generated by Django 4.2 on 2024-02-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partit',
            name='resultat_local',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partit',
            name='resultat_visitant',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
